-- TABLES FOR WHISK APP DATABASE:

-- * users
-- * books
-- * recipes
-- * recipes_books
-- * recipes_tried
-- * calendar
-- * notes
-- * reviews

CREATE TABLE users (
  username VARCHAR(25) PRIMARY KEY,
  password TEXT NOT NULL,
  firstName TEXT NOT NULL,
  lastName TEXT NOT NULL,
  email TEXT NOT NULL
    CHECK (position('@' IN email) > 1),
  isAdmin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE books (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  username VARCHAR(25) NOT NULL
    REFERENCES users ON DELETE CASCADE
);

CREATE TABLE recipes (
  label VARCHAR NOT NULL,
  image VARCHAR NOT NULL,
  uri VARCHAR PRIMARY KEY
);


CREATE TABLE recipes_books (
  recipeURI VARCHAR NOT NULL
    REFERENCES recipes ON DELETE CASCADE,
  bookId INTEGER NOT NULL
    REFERENCES books ON DELETE CASCADE
);

-- -- // tables: recipes_tried
CREATE TABLE recipes_tried (
    id INTEGER NOT NULL PRIMARY KEY,
  recipeURI VARCHAR NOT NULL
    REFERENCES recipes ON DELETE CASCADE,
  username VARCHAR(25) NOT NULL
    REFERENCES users ON DELETE CASCADE
);

CREATE TABLE calendars (
   username VARCHAR(25) NOT NULL
    REFERENCES users ON DELETE CASCADE,
   monday VARCHAR DEFAULT null
    REFERENCES recipes ON DELETE CASCADE,
   tuesday VARCHAR DEFAULT null
    REFERENCES recipes ON DELETE CASCADE,
   wednesday VARCHAR DEFAULT null
    REFERENCES recipes ON DELETE CASCADE,
   thursday VARCHAR DEFAULT null
    REFERENCES recipes ON DELETE CASCADE,
   friday VARCHAR DEFAULT null
    REFERENCES recipes ON DELETE CASCADE,
   saturday VARCHAR DEFAULT null
    REFERENCES recipes ON DELETE CASCADE,
   sunday VARCHAR DEFAULT null
    REFERENCES recipes ON DELETE CASCADE
);

-- -- // tables: notes
CREATE TABLE notes (
    id INTEGER NOT NULL PRIMARY KEY,
  recipeURI VARCHAR NOT NULL
    REFERENCES recipes ON DELETE CASCADE,
  username VARCHAR(25) NOT NULL
    REFERENCES users ON DELETE CASCADE,
noteText VARCHAR NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP

);

-- -- // tables reviews
CREATE TABLE reviews (
    id INTEGER NOT NULL PRIMARY KEY,
  recipeURI VARCHAR NOT NULL
    REFERENCES recipes ON DELETE CASCADE,
  username VARCHAR(25) NOT NULL
    REFERENCES users ON DELETE CASCADE,
reviewText VARCHAR NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP

);

-- tables ratings   (STARS SEPARATE FROM REVIEWS)
CREATE TABLE ratings (
  id SERIAL PRIMARY KEY,
  recipeURI VARCHAR NOT NULL
    REFERENCES recipes ON DELETE CASCADE,
    username VARCHAR(25) NOT NULL
    REFERENCES users ON DELETE CASCADE,
  starRating INTEGER CHECK (starRating >=0),
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)